const PATTERN_NAME = "^[A-Za-zА-Яа-яё -]+$";
const INPUT_VALIDATION_MESSAGE_DEFAULT = "Введите данные в указанном формате.";
const INPUT_VALIDATION_MESSAGE_NAME = "Имя должно содержать только латиницу, кириллицу, пробел или дефис";
const INPUT_VALIDATION_MESSAGE_EMAIL = "Введите данные в формате e-mail";
const SERVER_ERROR_MESSAGE_CONFLICT = "Пользователь с таким email уже существует.";
const SERVER_ERROR_MESSAGE_VALIDATION = "Переданы некорректные данные.";
const SERVER_ERROR_MESSAGE_500 = "На сервере произошла ошибка.";
const SERVER_ERROR_MESSAGE_TOKEN = "При авторизации произошла ошибка.";
const SERVER_ERROR_MESSAGE_LOGIN = "Неправильные email или пароль.";
const SERVER_ERROR_MESSAGE_USER_UPDATE  = "При обновлении профиля произошла ошибка.";
const SHORT_MOVIE_DURATION = 40;
const SCREEN_WIDTH_LAPTOP = 1279;
const SCREEN_WIDTH_TABLET = 656;
const CARDS_FIRST_RENDERED_LAPTOP = 12;
const CARDS_FIRST_RENDERED_TABLET = 8;
const CARDS_FIRST_RENDERED_MOBILE = 5;
const CARDS_SHOW_MORE_TABLET_MOBILE = 2;
const CARDS_SHOW_MORE_LAPTOP = 3;

module.exports = {
  PATTERN_NAME,
  INPUT_VALIDATION_MESSAGE_DEFAULT,
  INPUT_VALIDATION_MESSAGE_NAME,
  INPUT_VALIDATION_MESSAGE_EMAIL,
  SERVER_ERROR_MESSAGE_CONFLICT,
  SERVER_ERROR_MESSAGE_VALIDATION,
  SERVER_ERROR_MESSAGE_500,
  SERVER_ERROR_MESSAGE_TOKEN,
  SERVER_ERROR_MESSAGE_LOGIN,
  SERVER_ERROR_MESSAGE_USER_UPDATE,
  SHORT_MOVIE_DURATION,
  SCREEN_WIDTH_LAPTOP,
  SCREEN_WIDTH_TABLET,
  CARDS_FIRST_RENDERED_LAPTOP,
  CARDS_FIRST_RENDERED_TABLET,
  CARDS_FIRST_RENDERED_MOBILE,
  CARDS_SHOW_MORE_TABLET_MOBILE,
  CARDS_SHOW_MORE_LAPTOP
};